package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// InteractionBindConfig interaction bind config
// swagger:model InteractionBindConfig
type InteractionBindConfig struct {

	// handle
	// Required: true
	Handle interface{} `json:"handle"`
}

// Validate validates this interaction bind config
func (m *InteractionBindConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHandle(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InteractionBindConfig) validateHandle(formats strfmt.Registry) error {

	return nil
}
