package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAllImagesParams creates a new ListAllImagesParams object
// with the default values initialized.
func NewListAllImagesParams() *ListAllImagesParams {
	var ()
	return &ListAllImagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllImagesParamsWithTimeout creates a new ListAllImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllImagesParamsWithTimeout(timeout time.Duration) *ListAllImagesParams {
	var ()
	return &ListAllImagesParams{

		timeout: timeout,
	}
}

// NewListAllImagesParamsWithContext creates a new ListAllImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllImagesParamsWithContext(ctx context.Context) *ListAllImagesParams {
	var ()
	return &ListAllImagesParams{

		Context: ctx,
	}
}

// NewListAllImagesParamsWithHTTPClient creates a new ListAllImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllImagesParamsWithHTTPClient(client *http.Client) *ListAllImagesParams {
	var ()
	return &ListAllImagesParams{
		HTTPClient: client,
	}
}

/*ListAllImagesParams contains all the parameters to send to the API endpoint
for the list all images operation typically these are written to a http.Request
*/
type ListAllImagesParams struct {

	/*StoreName*/
	StoreName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all images params
func (o *ListAllImagesParams) WithTimeout(timeout time.Duration) *ListAllImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all images params
func (o *ListAllImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all images params
func (o *ListAllImagesParams) WithContext(ctx context.Context) *ListAllImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all images params
func (o *ListAllImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all images params
func (o *ListAllImagesParams) WithHTTPClient(client *http.Client) *ListAllImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all images params
func (o *ListAllImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStoreName adds the storeName to the list all images params
func (o *ListAllImagesParams) WithStoreName(storeName string) *ListAllImagesParams {
	o.SetStoreName(storeName)
	return o
}

// SetStoreName adds the storeName to the list all images params
func (o *ListAllImagesParams) SetStoreName(storeName string) {
	o.StoreName = storeName
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param store_name
	if err := r.SetPathParam("store_name", o.StoreName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
