package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/containerd/containerd/plapi/models"
)

// RemoveImageReader is a Reader for the RemoveImage structure.
type RemoveImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewRemoveImageCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRemoveImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRemoveImageCreated creates a RemoveImageCreated with default headers values
func NewRemoveImageCreated() *RemoveImageCreated {
	return &RemoveImageCreated{}
}

/*RemoveImageCreated handles this case with default header values.

Image successfully deleted
*/
type RemoveImageCreated struct {
	Payload string
}

func (o *RemoveImageCreated) Error() string {
	return fmt.Sprintf("[DELETE /snapshot/{store_name}][%d] removeImageCreated  %+v", 201, o.Payload)
}

func (o *RemoveImageCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveImageDefault creates a RemoveImageDefault with default headers values
func NewRemoveImageDefault(code int) *RemoveImageDefault {
	return &RemoveImageDefault{
		_statusCode: code,
	}
}

/*RemoveImageDefault handles this case with default header values.

error
*/
type RemoveImageDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the remove image default response
func (o *RemoveImageDefault) Code() int {
	return o._statusCode
}

func (o *RemoveImageDefault) Error() string {
	return fmt.Sprintf("[DELETE /snapshot/{store_name}][%d] RemoveImage default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
