package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnpackImageParams creates a new UnpackImageParams object
// with the default values initialized.
func NewUnpackImageParams() *UnpackImageParams {
	var ()
	return &UnpackImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnpackImageParamsWithTimeout creates a new UnpackImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnpackImageParamsWithTimeout(timeout time.Duration) *UnpackImageParams {
	var ()
	return &UnpackImageParams{

		timeout: timeout,
	}
}

// NewUnpackImageParamsWithContext creates a new UnpackImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnpackImageParamsWithContext(ctx context.Context) *UnpackImageParams {
	var ()
	return &UnpackImageParams{

		Context: ctx,
	}
}

// NewUnpackImageParamsWithHTTPClient creates a new UnpackImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnpackImageParamsWithHTTPClient(client *http.Client) *UnpackImageParams {
	var ()
	return &UnpackImageParams{
		HTTPClient: client,
	}
}

/*UnpackImageParams contains all the parameters to send to the API endpoint
for the unpack image operation typically these are written to a http.Request
*/
type UnpackImageParams struct {

	/*ImageFile*/
	ImageFile io.ReadCloser
	/*ImageID*/
	ImageID string
	/*Metadatakey*/
	Metadatakey *string
	/*Metadataval*/
	Metadataval *string
	/*ParentID*/
	ParentID string
	/*StoreName*/
	StoreName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unpack image params
func (o *UnpackImageParams) WithTimeout(timeout time.Duration) *UnpackImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unpack image params
func (o *UnpackImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unpack image params
func (o *UnpackImageParams) WithContext(ctx context.Context) *UnpackImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unpack image params
func (o *UnpackImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unpack image params
func (o *UnpackImageParams) WithHTTPClient(client *http.Client) *UnpackImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unpack image params
func (o *UnpackImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageFile adds the imageFile to the unpack image params
func (o *UnpackImageParams) WithImageFile(imageFile io.ReadCloser) *UnpackImageParams {
	o.SetImageFile(imageFile)
	return o
}

// SetImageFile adds the imageFile to the unpack image params
func (o *UnpackImageParams) SetImageFile(imageFile io.ReadCloser) {
	o.ImageFile = imageFile
}

// WithImageID adds the imageID to the unpack image params
func (o *UnpackImageParams) WithImageID(imageID string) *UnpackImageParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the unpack image params
func (o *UnpackImageParams) SetImageID(imageID string) {
	o.ImageID = imageID
}

// WithMetadatakey adds the metadatakey to the unpack image params
func (o *UnpackImageParams) WithMetadatakey(metadatakey *string) *UnpackImageParams {
	o.SetMetadatakey(metadatakey)
	return o
}

// SetMetadatakey adds the metadatakey to the unpack image params
func (o *UnpackImageParams) SetMetadatakey(metadatakey *string) {
	o.Metadatakey = metadatakey
}

// WithMetadataval adds the metadataval to the unpack image params
func (o *UnpackImageParams) WithMetadataval(metadataval *string) *UnpackImageParams {
	o.SetMetadataval(metadataval)
	return o
}

// SetMetadataval adds the metadataval to the unpack image params
func (o *UnpackImageParams) SetMetadataval(metadataval *string) {
	o.Metadataval = metadataval
}

// WithParentID adds the parentID to the unpack image params
func (o *UnpackImageParams) WithParentID(parentID string) *UnpackImageParams {
	o.SetParentID(parentID)
	return o
}

// SetParentID adds the parentId to the unpack image params
func (o *UnpackImageParams) SetParentID(parentID string) {
	o.ParentID = parentID
}

// WithStoreName adds the storeName to the unpack image params
func (o *UnpackImageParams) WithStoreName(storeName string) *UnpackImageParams {
	o.SetStoreName(storeName)
	return o
}

// SetStoreName adds the storeName to the unpack image params
func (o *UnpackImageParams) SetStoreName(storeName string) {
	o.StoreName = storeName
}

// WriteToRequest writes these params to a swagger request
func (o *UnpackImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ImageFile); err != nil {
		return err
	}

	// query param image_id
	qrImageID := o.ImageID
	qImageID := qrImageID
	if qImageID != "" {
		if err := r.SetQueryParam("image_id", qImageID); err != nil {
			return err
		}
	}

	if o.Metadatakey != nil {

		// query param metadatakey
		var qrMetadatakey string
		if o.Metadatakey != nil {
			qrMetadatakey = *o.Metadatakey
		}
		qMetadatakey := qrMetadatakey
		if qMetadatakey != "" {
			if err := r.SetQueryParam("metadatakey", qMetadatakey); err != nil {
				return err
			}
		}

	}

	if o.Metadataval != nil {

		// query param metadataval
		var qrMetadataval string
		if o.Metadataval != nil {
			qrMetadataval = *o.Metadataval
		}
		qMetadataval := qrMetadataval
		if qMetadataval != "" {
			if err := r.SetQueryParam("metadataval", qMetadataval); err != nil {
				return err
			}
		}

	}

	// query param parent_id
	qrParentID := o.ParentID
	qParentID := qrParentID
	if qParentID != "" {
		if err := r.SetQueryParam("parent_id", qParentID); err != nil {
			return err
		}
	}

	// path param store_name
	if err := r.SetPathParam("store_name", o.StoreName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
